check-leaks: false
color: true
diff: true
full-trace: true
reporter: '@serenity-js/mocha'
require:
  - ts-node/register
  - spec/support/serenity.config.ts
spec: 'spec/**/*.spec.ts'
timeout: 10000
v8-stack-trace-limit: 1000
